# injury_database.py

ACTION_NAME_MAP = {
    "spike": "扣球",
    "block": "攔網",
    "serve": "發球",
    "receive": "接球",
    "set": "托球",
}


INJURY_DATABASE = {
    "shoulder_impingement": {
        "position": "肩膀",
        "name_zh": "肩峰下夾擠症候群",
        "name_en": "Subacromial Impingement Syndrome",
        "cause_plain": "手臂反覆高舉、肩胛控制不足或擊球點太低時，肩部肌腱容易被擠壓。",
        "advice": "先降低連續揮臂量，練習肩胛上旋與胸椎伸展，擊球時讓手肘和手腕在身體前上方完成。",
        "source": "https://www.mayoclinic.org/search/search-results?q=shoulder%20impingement",
    },
    "rotator_cuff_overload": {
        "position": "肩膀",
        "name_zh": "旋轉肌袖過度負荷",
        "name_en": "Rotator Cuff Overload",
        "cause_plain": "扣球或發球時若只用肩膀硬甩，缺少軀幹轉動與下肢發力，旋轉肌袖會承受過多壓力。",
        "advice": "把發力順序改成腳、髖、軀幹、肩、手臂，並加入外旋肌群與肩胛穩定訓練。",
        "source": "https://orthoinfo.aaos.org/en/diseases--conditions/rotator-cuff-tears/",
    },
    "elbow_tendinopathy": {
        "position": "手肘",
        "name_zh": "手肘肌腱過度使用",
        "name_en": "Elbow Tendinopathy",
        "cause_plain": "手肘角度太小或手腕代償太多，會讓前臂肌腱反覆拉扯。",
        "advice": "擊球前讓手肘打開，手腕保持穩定，避免只靠前臂甩球。",
        "source": "https://my.clevelandclinic.org/health/diseases/7049-tennis-elbow-lateral-epicondylitis",
    },
    "de_quervain": {
        "position": "手腕/拇指",
        "name_zh": "腕部肌腱發炎風險",
        "name_en": "Wrist Tendon Irritation",
        "cause_plain": "托球或接球時手腕位置太低，容易用手腕硬撐球，造成腕部肌腱壓力增加。",
        "advice": "讓手腕提到額頭上方或身體前方，手指放鬆成杯狀，用膝蓋和核心協助推送。",
        "source": "https://www.webmd.com/rheumatoid-arthritis/de-quervains-disease",
    },
    "acl_injury": {
        "position": "膝蓋",
        "name_zh": "前十字韌帶受傷風險",
        "name_en": "ACL Injury Risk",
        "cause_plain": "落地或蹲低時膝蓋過度內夾、膝角度控制不佳，會增加膝關節剪力。",
        "advice": "落地時膝蓋對準第二腳趾，髖部往後坐，避免膝蓋突然往內倒。",
        "source": "https://medlineplus.gov/acl.html",
    },
    "jumper_knee": {
        "position": "膝蓋",
        "name_zh": "跳躍膝/髕腱負荷",
        "name_en": "Patellar Tendinopathy",
        "cause_plain": "反覆跳躍、落地太硬或膝蓋彎曲控制不足，會讓髕腱負擔增加。",
        "advice": "練習安靜落地、髖膝踝一起吸收衝擊，逐步增加跳躍量。",
        "source": "https://www.nhs.uk/conditions/knee-pain/",
    },
    "ankle_sprain": {
        "position": "腳踝",
        "name_zh": "腳踝扭傷風險",
        "name_en": "Ankle Sprain Risk",
        "cause_plain": "起跳或落地時腳踝不穩，尤其踩到他人腳或單腳落地，容易造成扭傷。",
        "advice": "加入單腳平衡、提踵和落地控制訓練；比賽時注意落地空間。",
        "source": "https://www.healthline.com/health/sprained-ankle",
    },
    "low_back_overload": {
        "position": "下背",
        "name_zh": "下背過度代償",
        "name_en": "Low Back Overload",
        "cause_plain": "發球或扣球時若過度拱腰，而不是用髖與胸椎旋轉，腰椎壓力會增加。",
        "advice": "收住肋骨、核心出力，練習髖部轉動和胸椎旋轉，不要只用腰往後折。",
        "source": "https://www.health.harvard.edu/pain/low-back-pain",
    },
    "setting_hands_not_detected": {
        "title": "托球手部未完整入鏡",
        "risk_level": "低",
        "what_it_means": "系統沒有同時看到兩隻手，托球手型判斷會不完整。",
        "fix_now": ["讓雙手、額頭和球都保持在鏡頭內。", "使用廣角或把手機放遠一點。"],
        "drills": ["原地自托 30 秒，確認雙手都在額頭前上方。"],
        "video_keywords": "volleyball setting hand position tutorial",
        "video_url": "https://www.youtube.com/results?search_query=volleyball+setting+hand+position+tutorial",
    },
    "setting_fingers_closed": {
        "title": "托球手指張開不足",
        "risk_level": "中",
        "what_it_means": "手指太收時容易用掌心或手腕頂球，方向不穩，也可能增加手腕壓力。",
        "fix_now": ["雙手形成三角窗，手指自然張開成杯狀。", "觸球時用指腹緩衝，不要用掌心拍球。"],
        "drills": ["靠牆短距離托球 2 組，每組 20 下。"],
        "video_keywords": "volleyball setting fingers triangle hand shape",
        "video_url": "https://www.youtube.com/results?search_query=volleyball+setting+fingers+triangle+hand+shape",
    },
    "setting_hand_spacing_bad": {
        "title": "托球雙手距離不理想",
        "risk_level": "低到中",
        "what_it_means": "雙手太近會夾球，太開會失去控制，出球方向容易飄。",
        "fix_now": ["雙手保持在額頭前上方，拇指和食指形成穩定三角形。"],
        "drills": ["自拋自托，注意雙手距離固定。"],
        "video_keywords": "volleyball setting hand spacing drill",
        "video_url": "https://www.youtube.com/results?search_query=volleyball+setting+hand+spacing+drill",
    },
    "setting_hands_unbalanced": {
        "title": "托球雙手高度不一致",
        "risk_level": "中",
        "what_it_means": "左右手高度差太大時，球容易旋轉或偏向一側。",
        "fix_now": ["雙手同時接球、同時推出，避免一隻手先碰球。"],
        "drills": ["靠牆托球，觀察球是否直上直下。"],
        "video_keywords": "volleyball setting no spin hand balance",
        "video_url": "https://www.youtube.com/results?search_query=volleyball+setting+no+spin+hand+balance",
    },
    "lobster_receive_risk": {
        "title": "吃蘿蔔風險偏高",
        "risk_level": "中到高",
        "what_it_means": "手臂平台太軟、手肘彎曲或身體沒有降下來時，球容易卡在前臂或直接噴飛。",
        "fix_now": ["手肘伸直鎖住平台，肩膀放鬆往前送。", "用腳步移到球後方，不要只伸手撈球。"],
        "drills": ["低姿勢平台定格 2 組，每組 10 秒。", "拋球接平台，要求球直上不旋轉。"],
        "video_keywords": "volleyball passing platform avoid shank",
        "video_url": "https://www.youtube.com/results?search_query=volleyball+passing+platform+avoid+shank",
    },
    "receive_platform_unbalanced": {
        "title": "接球平台左右不平",
        "risk_level": "中",
        "what_it_means": "左右手高度不同會讓平台變斜，球容易偏向一側。",
        "fix_now": ["兩手併攏後讓前臂形成平面，接球前先停住平台。"],
        "drills": ["平台接球定格，檢查兩側前臂是否同高。"],
        "video_keywords": "volleyball passing platform angle drill",
        "video_url": "https://www.youtube.com/results?search_query=volleyball+passing+platform+angle+drill",
    },
    "receive_hands_apart": {
        "title": "接球雙手距離過開",
        "risk_level": "中",
        "what_it_means": "雙手沒有併好時，平台面積會變小，容易吃蘿蔔或讓球亂彈。",
        "fix_now": ["接球前先把雙手併好，手腕下壓，前臂保持同一平面。"],
        "drills": ["原地平台維持 20 秒，確認雙手不分開。"],
        "video_keywords": "volleyball forearm passing hands together drill",
        "video_url": "https://www.youtube.com/results?search_query=volleyball+forearm+passing+hands+together+drill",
    },
}


ERROR_TO_INJURY = {
    "elbow_not_straight": ["elbow_tendinopathy"],
    "elbow_bad": ["elbow_tendinopathy"],
    "elbow_position_bad": ["elbow_tendinopathy"],
    "hands_not_high": ["shoulder_impingement", "rotator_cuff_overload"],
    "shoulder_low": ["shoulder_impingement", "rotator_cuff_overload"],
    "wrist_low": ["de_quervain"],
    "setting_hands_not_detected": ["de_quervain"],
    "setting_fingers_closed": ["de_quervain"],
    "setting_hand_spacing_bad": ["de_quervain"],
    "setting_hands_unbalanced": ["de_quervain", "elbow_tendinopathy"],
    "lobster_receive_risk": ["elbow_tendinopathy", "de_quervain"],
    "receive_platform_unbalanced": ["elbow_tendinopathy"],
    "receive_hands_apart": ["elbow_tendinopathy", "de_quervain"],
    "knee_too_bent": ["acl_injury", "jumper_knee", "ankle_sprain"],
    "knee_bad": ["acl_injury", "jumper_knee", "ankle_sprain"],
}


ERROR_FEEDBACK = {
    "elbow_not_straight": {
        "title": "手肘沒有完全伸展",
        "risk_level": "中",
        "what_it_means": "攔網或擊球時手臂沒有打開，會讓手肘和肩膀一起代償。",
        "fix_now": [
            "把手肘往上推直，不要只把手腕伸出去。",
            "想像用肩胛把手臂送高，手肘最後再鎖住。",
            "若手肘疼痛，先降低連續攔網或扣球次數。",
        ],
        "drills": [
            "牆面手臂伸直觸碰 2 組，每組 10 次。",
            "彈力帶肩胛上旋與外旋 2 組，每組 12 次。",
        ],
        "video_keywords": "volleyball blocking arm extension drill",
        "video_url": "https://www.youtube.com/results?search_query=volleyball+blocking+arm+extension+drill",
    },
    "elbow_bad": {
        "title": "手肘角度不足",
        "risk_level": "中",
        "what_it_means": "手肘太彎時，力量容易卡在前臂，扣球或發球的出力鏈會斷掉。",
        "fix_now": [
            "準備擊球時讓手肘高於肩膀，擊球瞬間往前上方伸展。",
            "不要只甩前臂，先用腳和髖部帶動身體轉向球。",
            "手腕保持放鬆，但不要用手腕硬折補力量。",
        ],
        "drills": [
            "跪姿或站姿拋牆扣球動作 2 組，每組 8 次。",
            "慢速空揮，確認手肘高點和伸展路徑。",
        ],
        "video_keywords": "volleyball spiking arm swing elbow high tutorial",
        "video_url": "https://www.youtube.com/results?search_query=volleyball+spiking+arm+swing+elbow+high+tutorial",
    },
    "elbow_position_bad": {
        "title": "托球手肘位置不穩",
        "risk_level": "低到中",
        "what_it_means": "托球時手肘過開或過夾，會讓手腕承擔太多力量，也會影響出球方向。",
        "fix_now": [
            "雙手在額頭前上方形成三角形，手肘自然打開。",
            "用膝蓋伸展和核心把球送出去，手腕只做最後微調。",
        ],
        "drills": [
            "原地自托 30 秒，確認球在額頭前方。",
            "靠牆托球 2 組，每組 20 下。",
        ],
        "video_keywords": "volleyball setting hand position elbow technique",
        "video_url": "https://www.youtube.com/results?search_query=volleyball+setting+hand+position+elbow+technique",
    },
    "hands_not_high": {
        "title": "手沒有舉到足夠高度",
        "risk_level": "中",
        "what_it_means": "攔網或托球時手太低，容易讓肩膀夾擠，也會錯過最佳觸球點。",
        "fix_now": [
            "先把胸口打開，肩胛往上旋，再把手送高。",
            "眼睛看球的同時，讓雙手提早到位，不要等球到身上才抬手。",
        ],
        "drills": [
            "牆面滑手 wall slide 2 組，每組 10 次。",
            "原地小跳攔網手型 2 組，每組 8 次。",
        ],
        "video_keywords": "volleyball blocking hand position reach high drill",
        "video_url": "https://www.youtube.com/results?search_query=volleyball+blocking+hand+position+reach+high+drill",
    },
    "shoulder_low": {
        "title": "肩膀/手臂高度偏低",
        "risk_level": "中",
        "what_it_means": "擊球點偏低時，肩膀容易用夾擠姿勢出力，球也較容易下網或失控。",
        "fix_now": [
            "提早移動到球下方，讓擊球點在身體前上方。",
            "扣球前用非慣用手指向球，幫助身體對準與拉高擊球點。",
        ],
        "drills": [
            "拋球找最高擊球點 2 組，每組 10 次。",
            "肩胛控制加彈力帶外旋 2 組，每組 12 次。",
        ],
        "video_keywords": "volleyball hitting contact point shoulder high tutorial",
        "video_url": "https://www.youtube.com/results?search_query=volleyball+hitting+contact+point+shoulder+high+tutorial",
    },
    "wrist_low": {
        "title": "手腕低於頭部",
        "risk_level": "低到中",
        "what_it_means": "托球時手腕太低，球會壓到手腕與拇指，方向也比較不穩。",
        "fix_now": [
            "手提前到額頭前上方，等球進入視線上緣再送出。",
            "保持手指柔軟，避免用掌心或手腕硬頂。",
        ],
        "drills": [
            "自拋自托，球只離手 30 到 50 公分。",
            "靠牆短距離托球，維持手腕在額頭上方。",
        ],
        "video_keywords": "volleyball setting wrist above forehead drill",
        "video_url": "https://www.youtube.com/results?search_query=volleyball+setting+wrist+above+forehead+drill",
    },
    "knee_too_bent": {
        "title": "膝蓋彎曲過多或控制不足",
        "risk_level": "中到高",
        "what_it_means": "膝蓋過度彎曲或塌陷，可能代表落地吸震不足、髖部沒有一起出力。",
        "fix_now": [
            "落地時髖部往後坐，膝蓋對準腳尖，不要往內夾。",
            "用雙腳平均承重，聽起來要安靜落地。",
            "如果膝蓋痛或腫，停止跳躍訓練並尋求專業評估。",
        ],
        "drills": [
            "跳落定格 stick landing 2 組，每組 6 次。",
            "徒手深蹲到椅子高度 2 組，每組 10 次。",
        ],
        "video_keywords": "volleyball landing mechanics knee alignment drill",
        "video_url": "https://www.youtube.com/results?search_query=volleyball+landing+mechanics+knee+alignment+drill",
    },
    "knee_bad": {
        "title": "膝蓋角度不理想",
        "risk_level": "中",
        "what_it_means": "膝蓋角度太直會吸震不足，太彎或內夾則可能增加韌帶與髕腱壓力。",
        "fix_now": [
            "起跳和落地時讓髖、膝、踝一起彎曲。",
            "膝蓋保持朝向腳尖，核心穩住，不要左右晃。",
        ],
        "drills": [
            "分腿蹲 2 組，每邊 8 次。",
            "低高度跳箱落地控制 2 組，每組 6 次。",
        ],
        "video_keywords": "volleyball knee alignment landing jump training",
        "video_url": "https://www.youtube.com/results?search_query=volleyball+knee+alignment+landing+jump+training",
    },
}
